### ISSUE TITLE
Immutable

### ISSUE THREAD

**Issue by pjebs** [hashicorp/go-immutable-radix#33]
What is meant by immutable in this context. I see insert and delete functions in the API.

**Comment by FrankReh** [comment]
I also had this question before. Looking at it again, I wonder if that description comes from the fact that a transaction is supported (type Txn) which I think means within the transaction, the tree access is kept consistent. That seems to be a big difference between this implementation and the simpler go-radix.

**Comment by banks** [comment]
It's immutable in that every modification creates a whole new tree.

It is more efficient that a full copy since we will re-use any existing tree nodes that haven't changed in the new tree, but any reader that is reading the old tree will still see the old version and will keep those old nodes from being garbage collected until they are finished with them and drop the pointer to the tree root.

**Comment by ianzhang1988** [comment]
Would be nice if put this explanation in readme.
